spring:
  application:
    name: @project.artifactId@
  profiles:
    active: local
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
mybatis:
  mapper-locations: classpath:/mappers/**/*Mapper.xml
---
spring:
  profiles: local
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: dengbin
    password: